# Generated by Django 4.1.6 on 2023-02-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_amount_remove_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, related_name='ingredients', to='recipes.amount', verbose_name='Ингредиенты'),
        ),
    ]
